services:
  oracle-training:
    image: ghcr.io/jeoliveira045/oracle-db:latest
    ports:
      - 1521:1521
    volumes:
      - ./src/main/resources/docker/oracle/:/docker-entrypoint-initdb.d/startup

