CONNECT SYSTEM/oracle;

ALTER SESSION SET CONTAINER = ORCLPDB1;
CREATE TABLESPACE TREINO_TBS DATAFILE '/opt/oracle/oradata/ORCLCDB/ORCLPDB1/treinotbs01.dbf' SIZE 100M ONLINE;
CREATE TABLESPACE IDX_CONTROLE_TBS DATAFILE '/opt/oracle/oradata/ORCLCDB/ORCLPDB1/idx_treinotbs01.dbf' SIZE 100M;
CREATE USER TREINO IDENTIFIED BY TREINO DEFAULT TABLESPACE TREINO_TBS TEMPORARY TABLESPACE TEMP;
GRANT CREATE SESSION, ALTER SESSION, CREATE VIEW, CREATE TABLE, CREATE SEQUENCE TO TREINO;
GRANT CREATE SYNONYM, CREATE DATABASE LINK, UNLIMITED TABLESPACE TO TREINO;
ALTER USER TREINO QUOTA UNLIMITED ON TREINO_TBS;
